### ISSUE TITLE
Long critical path through the DW Converters

### ISSUE THREAD

**Issue by suehtamacv** [pulp-platform/axi#123]
Atomics are at the critical path of the DW Converters. 

Upon receiving an atomic request on the AW channel, the request is forwarded as a pseudo-AR request to one of the read up/downsizers, which will be responsible for handling the atomic responses on the R channel. The decision to forward the AW request to the read up/downsizers, the arbitration of which up/downsizer will handle the atomic request, and the logic of the up/downsizer upon receiving a new request, all that happens in a single cycle.

Pipelining this path might lead to max operating frequency improvements for the DW Converters, at the expense of lower performance for atomic operations.

**Comment by accuminium** [comment]
Fixed by #124.
