### ISSUE TITLE
axi_dma

### ISSUE THREAD

**Issue by msaideroglu** [pulp-platform/axi#125]
I can not find axi_dma module. Where can I find it?

**Comment by accuminium** [comment]
The `axi_dma` module has not yet been included in a release. It is currently being integrated in PR #110. You can preview the code there.

**Comment by bufans** [comment]
Hi, where can I find the last level cache module?

**Comment by accuminium** [comment]
The LLC is being integrated in PR [#33](https://github.com/pulp-platform/axi/pull/33).

**Comment by bufans** [comment]
> The LLC is being integrated in PR [#33](https://github.com/pulp-platform/axi/pull/33).

Thank you very much.  I saw the LLC code.
