### ISSUE TITLE
Build and deploy documentation is failing.

### ISSUE THREAD

**Issue by WRoenninger** [pulp-platform/axi#129]
When the CI runs, the build and deploy documentation fails with following output in `Determine documentation target folder`:

```bash
Run if echo $GITHUB_REF | grep -qE '^refs/(heads|tags)'; then
Error: Unable to process command '::set-env name=DOC_TARGET::axi_to_mem' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by WRoenninger** [comment]
On that note, it would be nice to add the link to the automatic generated documentation to the top README.

**Comment by accuminium** [comment]
Indeed, thanks for reporting @WRoenninger!
