### ISSUE TITLE
the error when run axi_intercon_gen.py

### ISSUE THREAD

**Issue by menglinhan** [pulp-platform/axi#222]
Traceback (most recent call last):
  File "./scripts/axi_intercon_gen.py", line 463, in <module>
    g = AxiIntercon(name, sys.argv[1])
IndexError: list index out of range

hello, when I run the script of axi_intercon_gen.py, can you tell me how to fix this issue? thanks

**Comment by andreaskurth** [comment]
Duplicate of #167.
