### ISSUE TITLE
Query: Max number of outstanding read requests

### ISSUE THREAD

**Issue by msharmavikram** [pulp-platform/axi#23]
I am wondering what is the maximum number of outstanding read requests supported in the design? 
Xilinx AXI interconnects limits to 32 for MMAP interface and I am looking for one that can support up to 256. The spec as it is does not have a limitation.

**Comment by accuminium** [comment]
The maximum number of outstanding transactions differs per module, some modules do not have an upper limit at all.  I guess you are specifically interested in the interconnect?
