### ISSUE TITLE
Monitor modport on AXI_BUS and AXI_LITE interfaces

### ISSUE THREAD

**Issue by jmdeharor** [pulp-platform/axi#240]
Hello,

I think it would be useful to have a Monitor modport (all signals as `input`), I have several modules that need this feature and for the moment I have to modify the code myself everytime I clone the repo.

Do you think this could be added? I think other people might find this helpful, specially for debugging code based on axi pulp interfaces.
Thanks!

**Comment by andreaskurth** [comment]
Thanks for this suggestion, @jmdeharor.

There is already a `modport Monitor` for `AXI_BUS_DV`, but I agree that this would be useful also on the `AXI_BUS` and `AXI_LITE` interfaces. Would you be willing to contribute this in a PR?
