### ISSUE TITLE
Should we add an option to force aligned accesses of given `ax_size` in class `axi_rand_master`?

### ISSUE THREAD

**Issue by luca-valente** [pulp-platform/axi#282]
I find that having a parameter to only have aligned accesses could be useful in certain stages of development. 
I pushed an example in [this](https://github.com/pulp-platform/axi/commit/62031da947f48734cca7562c459f7af64a1298dd) branch. If you agree it is a feature worth mentioning, we could then also discuss the proper way to implement it.
Luca

**Comment by thommythomaso** [comment]
Merged #284. Closed.
