### ISSUE TITLE
Naming Scheme for IDs and Wrappers

### ISSUE THREAD

**Issue by zarubaf** [pulp-platform/axi#53]
Can we get a small contribution/style section on how we decided to name ports, interface wrapper and parameters of the modules? What do you think?

**Comment by fabianschuiki** [comment]
That's an excellent idea. Should we create a `CONTRIBUTING.md` file for this, or just add a section to the readme? We could also add a link to coding style guidelines.

**Comment by accuminium** [comment]
Good idea, thanks for the suggestion. How about adding a `CONTRIBUTING.md` that generally refers to the SystemVerilog Style Guide we use (by LowRISC) and specifically states that

- User-facing modules _must_ have SystemVerilog structs as AXI ports.
- User-facing modules _may_ come with a variant that has SystemVerilog interfaces as AXI ports. Such a variant module _must not_ implement any functionality except wiring its interfaces to the struct ports of the original module. The name of a variant _must_ be the name of the original module suffixed by `_intf`. Parameters of a variant must be formatted `ALL_CAPS`.

The rationale behind `ALL_CAPS` parameters for `_intf` modules is to provide a uniform "legacy" interface. I intend to change this for all `_intf` modules at once with the v1.0 release.

What do you think? Anything missing?

**Comment by fabianschuiki** [comment]
@accuminium: This sounds like a solid plan!

**Comment by zarubaf** [comment]
@accuminium That is perfect. Exactly what I was looking for. That can act as quick reference when implementing new modules! Thanks.
